### ISSUE TITLE
I have several errors, each time I get an error I have to restart my private server, otherwise I can not start！

### ISSUE THREAD

**Issue by leihen08** [ronancpl/MapleSolaxiaV2#132]
Here are a few wrong logs！

**Comment by leihen08** [comment]
exceptionCaught.txt
java.lang.NullPointerException
	at server.maps.MapleMapFactory.loadMapFromWz(MapleMapFactory.java:101)
	at server.maps.MapleMapFactory.getMap(MapleMapFactory.java:301)
	at net.server.channel.Channel$1.run(Channel.java:455)
	at server.TimerManager$LoggingSaveRunnable.run(TimerManager.java:144)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

---------------------------------

**Comment by leihen08** [comment]
npcs
1002000.txt
javax.script.ScriptException: sun.org.mozilla.javascript.internal.EcmaError: TypeError: Cannot read property "-3" from undefined (<Unknown source>#44) in <Unknown source> at line number 44
	at com.sun.script.javascript.RhinoScriptEngine.invoke(Unknown Source)
	at com.sun.script.javascript.RhinoScriptEngine.invokeFunction(Unknown Source)
	at scripting.npc.NPCScriptManager.action(NPCScriptManager.java:118)
	at net.server.channel.handlers.NPCMoreTalkHandler.handlePacket(NPCMoreTalkHandler.java:72)
	at net.MapleServerHandler.messageReceived(MapleServerHandler.java:159)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:690)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:407)
	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:236)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:410)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:710)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:664)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:653)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1124)
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: sun.org.mozilla.javascript.internal.EcmaError: TypeError: Cannot read property "-3" from undefined (<Unknown source>#44)
	at sun.org.mozilla.javascript.internal.ScriptRuntime.constructError(Unknown Source)
	at sun.org.mozilla.javascript.internal.ScriptRuntime.constructError(Unknown Source)
	at sun.org.mozilla.javascript.internal.ScriptRuntime.typeError(Unknown Source)
	at sun.org.mozilla.javascript.internal.ScriptRuntime.typeError2(Unknown Source)
	at sun.org.mozilla.javascript.internal.ScriptRuntime.undefReadError(Unknown Source)
	at sun.org.mozilla.javascript.internal.ScriptRuntime.getObjectIndex(Unknown Source)
	at sun.org.mozilla.javascript.internal.Interpreter.interpretLoop(Unknown Source)
	at sun.org.mozilla.javascript.internal.Interpreter.interpret(Unknown Source)
	at sun.org.mozilla.javascript.internal.InterpretedFunction.call(Unknown Source)
	at sun.org.mozilla.javascript.internal.ContextFactory.doTopCall(Unknown Source)
	at com.sun.script.javascript.RhinoScriptEngine$1.superDoTopCall(Unknown Source)
	at com.sun.script.javascript.RhinoScriptEngine$1.doTopCall(Unknown Source)
	at sun.org.mozilla.javascript.internal.ScriptRuntime.doTopCall(Unknown Source)
	at sun.org.mozilla.javascript.internal.InterpretedFunction.call(Unknown Source)
	... 26 more

---------------------------------

**Comment by leihen08** [comment]
PacketHandler
net.server.channel.handlers.RangedAttackHandler.txt
Error for player ; Solely on map ; 110020000 - account ; leihen
All: 2D 00 00 11 09 26 31 00 A5 57 62 FC E5 12 7D 45 5A 00 00 00 02 17 80 04 05 96 16 E3 01 00 00 00 00 1E 61 CA 9A 3B 06 81 01 01 68 00 A1 00 68 00 A1 00 F8 02 2D 0F 00 00 6D 5F DB 05 B8 01 B4 00 9A 01 98 00
Now: B8 01 B4 00 9A 01 98 00
java.lang.NullPointerException
	at net.server.channel.handlers.AbstractDealDamageHandler$AttackInfo.getAttackEffect(AbstractDealDamageHandler.java:136)
	at net.server.channel.handlers.RangedAttackHandler.handlePacket(RangedAttackHandler.java:104)
	at net.MapleServerHandler.messageReceived(MapleServerHandler.java:159)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:690)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.filter.codec.ProtocolCodecFilter$ProtocolDecoderOutputImpl.flush(ProtocolCodecFilter.java:407)
	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:236)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1200(DefaultIoFilterChain.java:47)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:765)
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:417)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:410)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:710)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:664)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:653)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1124)
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

---------------------------------

**Comment by leihen08** [comment]
After an error I have to restart the private server, otherwise unable to start localhost！

**Comment by ronancpl** [comment]
By whatever reason, the first log implies the WZ being used by server and client sides mismatch, or they are not those that has been provided here. A given mapid there does not have the "info" node on the server-side. I have checked with the provided WZs, and they all have an "info" node.

Regarding the 3rd log, AutoBan is not properly done. They kinda bug a lot, but they should not cause harm to the flow of the server. Covered that case now.

**Comment by leihen08** [comment]
Thank you for taking the time to deal with these problems!
I am learning java.
I have a question to ask you.
How can I translate English into my language? I tried to translate them, but it was garbled.

**Comment by ronancpl** [comment]
Not too sure about how to do it, tbh. Have you tried changing from ascii to your language? Idk if the localhost needs to be changes as well, probably that will be needed too.

**Comment by leihen08** [comment]
Thank you so much ronan!
I go to study and test！
