### ISSUE TITLE
char save currurptions with rings

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#24]
cant tell if it was a hacker on server using illegal rings or what not but i do have item level up enabled and i have spingleman rings dropping from mobs.

All: 05 00 02 00 00 49 8C 86 8F
Now: 49 8C 86 8F
java.lang.NullPointerException
	at tools.MaplePacketCreator.addCharStats(MaplePacketCreator.java:144)
	at tools.MaplePacketCreator.addCharEntry(MaplePacketCreator.java:318)
	at tools.MaplePacketCreator.getCharList(MaplePacketCreator.java:866)
	at client.MapleClient.sendCharList(MapleClient.java:155)
	at net.server.handlers.login.CharlistRequestHandler.handlePacket(CharlistRequestHandler.java:36)
	at net.MapleServerHandler.messageReceived(MapleServerHandler.java:139)

**Comment by ronancpl** [comment]
Null char name? Wtf

**Comment by resinate** [comment]
his ign was smoke dunno what happened
