### ISSUE TITLE
moveplayer in maple map error

### ISSUE THREAD

**Issue by resinate** [ronancpl/MapleSolaxiaV2#29]
coming from this line
MapleMapObject[] visibleObjectsNow = visibleObjects.toArray(new MapleMapObject[visibleObjects.size()]);

something about nextnode and collections

All: 29 00 00 66 1F 84 D7 C5 FC C6 FE 05 00 EE FC D8 FE 0D 01 0E 01 00 00 06 96 00 00 EE FC D9 FE 86 00 00 00 00 00 06 03 00 00 FC FC D9 FE 05 00 00 00 2F 00 08 B1 00 00 FC FC D9 FE 00 00 00 00 2F 00 08 78 00 00 F9 FC D9 FE AC FF 00 00 2F 00 03 3C 00 11 00 00 00 00 00 00 00 80 08 C5 FC C6 FE FC FC D9 FE
Now: 11 00 00 00 00 00 00 00 80 08 C5 FC C6 FE FC FC D9 FE
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source)
	at java.util.AbstractCollection.toArray(Unknown Source)
	at java.util.Collections$UnmodifiableCollection.toArray(Unknown Source)
	at server.maps.MapleMap.movePlayer(MapleMap.java:2420)
	at net.server.channel.handlers.MovePlayerHandler.handlePacket(MovePlayerHandler.java:37)
	at net.MapleServerHandler.messageReceived(MapleServerHandler.java:139)

**Comment by ExtremeDevilz** [comment]
dude stop spamming the issues log, either fix it or learn to fix it, this people are not your slaves.

**Comment by resinate** [comment]
devilz dont start drama here he told me to report any issues and he will have a look go away for last time. your not wanted here.

**Comment by ronancpl** [comment]
In a point, true, reporting issues is a nice thing. Another better is to point out them while planning up a solution for it, so that the issue list doesn't blow. Take that in mind, please.
