### ISSUE TITLE
[Suposto erro] Erro nos scripts de evento

### ISSUE THREAD

**Issue by vcoc** [ronancpl/MapleSolaxiaV2#7]
Eu baixei os arquivos pra eu voltar a mexer no solaxia e fiz tudo certinho (como eu costumava fazer antigamente) mas na hora de executar o cmd, tive erro em todos os scripts, vou por o erro abaixo, se for erro meu, me desculpe, só estou tentando ajudar. Mais uma coisa, poderia fazer ou me falar um tutorial em pt de como usar/instalar esse seu projeto? como usar o MobBookUpdate, MapleIdRetriever e etc, obg ronan!

Em C:\Users\Victor Calheiros\Downloads\MapleSolaxiaV2-master\logs\2017-05-15\error\invocable\t

Erros: Obs: todos os scripts deram o mesmo erro.

scripts/event/2xEvent.js
javax.script.ScriptException: ReferenceError: "importPackage" is not defined in <eval> at line number 34
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:454)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:150)
	at javax.script.AbstractScriptEngine.eval(Unknown Source)
	at scripting.AbstractScriptManager.getInvocable(AbstractScriptManager.java:70)
	at scripting.event.EventScriptManager.<init>(EventScriptManager.java:54)
	at net.server.channel.Channel.<init>(Channel.java:89)
	at net.server.Server.run(Server.java:196)
	at net.server.Server.main(Server.java:235)
Caused by: <eval>:34 ReferenceError: "importPackage" is not defined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1441)
	at jdk.nashorn.internal.scripts.Script$1$\^eval\_.:program(<eval>:34)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	... 9 more

**Comment by ronancpl** [comment]
Cara, esses erros geralmente estão associados com como todo o material que foi disponibilizado foi instalado na sua máquina e como eles estão se comunicando. Por ex, se vc estiver usando um Java 8 da vida aí complica ter suporte, pq já saiu do meu escopo (trabalho no Java 7).

Posso te falar td que vc precisa saber pra instalar td, mas pra isso é melhor arranjarmos um messenger. Tenta me achar no Google Hangouts, minha conta é rcpl2010. Vou tentar ajudá-lo na medida do possível.

**Comment by vcoc** [comment]
Não te encontrei lá, baixei o app e tudo mais, mas infelizmente não achei, você poderia tenta me adicionar? Meu nome e e-mail: Victor Calheiros DOC ou vcalheirosdoc@gmail.com
